image: 
  file: .gitpod.Dockerfile

tasks:
  - before: pip install -r docs/requirements.txt
    command: gp open .vscode/welcome.md

vscode:
  extensions:
    - ms-python.python
    - lextudio.restructuredtext
    - trond-snekvik.simple-rst
    - errata-ai.vale-server
    - eamodio.gitlens